### PR TITLE
Added checksum script

### PR DESCRIPTION
**Pull request by CleanMachine1**

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
Could you add a gh action that runs on every commit?

**Comment by CleanMachine1** [comment]
I mean, we could use https://github.com/actions/upload-artifact however that doesn't add it as a file, rather just something in the actual repo.

What do you think?

**Comment by Itai-Nelken** [comment]
You can make it push or create a new branch abd open a pr

https://stackoverflow.com/questions/55657835/is-there-a-way-to-push-changes-with-a-github-action

**Comment by CleanMachine1** [comment]
🤦 

Why didn't I think of that!

Good thinking :)

**Comment by CleanMachine1** [comment]
That will need a github secret/ Personal access token.

Maybe whoever owns this repo/org can make one, otherwise it will just have to be an artifact

**Comment by Itai-Nelken** [comment]
@Botspot

**Comment by CleanMachine1** [comment]
I have a better solution.

using hooks instead meaning there will be no new file in the repo however it means it would have to be enforced that everyone that commits adds something like this script

```

#! /bin/bash

sha256sum ./* > sha256sums.txt

git add sha256sums.txt
```
to this file here .git/hooks/pre-commit 

therefore whenever someone commits, the script auto runs.

We could add the script to copy and paste and a little tutorial on how to put in the correct place for anyone adding files to the repo.

**Comment by ryanfortner** [comment]
@CleanMachine1 @Itai-Nelken I think github actions already has a token every time it runs, so you won't need someone to make one. See this article: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Pull request closed without merging**
