### PR TITLE
use proper github actions details in `checksums.yml`

### PR DESCRIPTION
**Pull request by ryanfortner**

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
I reverted as it broke the builds, could you try to fix and open a new pr please?

**Comment by cycool29** [comment]
> I reverted as it broke the builds, could you try to fix and open a new pr please?

It doesn't broke, it is just because you didn't upload anything, so the shasums file remains same and it exited with 'nothing to commit'.

**Comment by ryanfortner** [comment]
@Itai-Nelken

**Comment by Itai-Nelken** [comment]
🤦‍♂️...
I reverted the revert and changed the action to exit cleanly if there are no changes

**Comment by Itai-Nelken** [comment]
(the fix isn't working...)

**Comment by ryanfortner** [comment]
https://github.com/Pi-Apps-Coders/files/pull/18?

**Pull request merged**
